### PR TITLE
Add list command

### PR DESCRIPTION
**Pull request by stephenfin**
Per $subject.

### CODE REVIEW

**Comment by mdbooth** [comment]
Nice! I'll look into the goreleaser error.

Please could you add usage and some example output to the README?

**Comment by mdbooth** [comment]
I think https://github.com/shiftstack/dev-cluster-dns/pull/2 fixes the goreleaser issue.

**Comment by mdbooth** [comment]
/retest

Ah, no bots here 🤷

**Comment by stephenfin** [comment]
> Please could you add usage and some example output to the README?

Done

**Review by mdbooth — APPROVED** [review]

**Pull request merged**
